### ISSUE TITLE
Update Sample Code to Use `x-square-hmacsha256-signature`

### ISSUE THREAD

**Issue by meihei3** [mootrichard/square-webhooks-sam-app#1]
Thank you for providing such awesome sample code!
The official documentation specifies the use of the `sha256` algorithm and the `x-square-hmacsha256-signature` header for HMAC. However, the sample code currently uses `sha1` and the `x-square-signature` header. I would like to update the sample code to align with the documentation by using the `x-square-hmacsha256-signature` header and `sha256` algorithm.
Thank you.

https://developer.squareup.com/docs/webhooks/step3validate

**Comment by mootrichard** [comment]
Awesome, yeah I'd more than welcome a PR to add the change if you are familiar with it.
